services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mudita-backend
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend:
    build:
      context: ./ui
      dockerfile: Dockerfile
    container_name: mudita-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://backend:8080
    depends_on:
      - backend
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: mudita-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./scripts:/docker-entrypoint.d
    environment:
      - BASIC_AUTH_USER=${BASIC_AUTH_USER:-admin}
      - BASIC_AUTH_PASSWORD=${BASIC_AUTH_PASSWORD}
    command: >
      sh -c "apk add --no-cache apache2-utils &&
             htpasswd -bc /etc/nginx/.htpasswd $${BASIC_AUTH_USER} $${BASIC_AUTH_PASSWORD} &&
             nginx -g 'daemon off;'"
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge